export const profile = {
  login: "jamland",
  id: 188568,
  avatar_url: "https://avatars3.githubusercontent.com/u/188568?v=4",
  name: "Andy Burkovetsky",
  blog: "dribbble.com/jamland",
  location: "Earth",
  bio: "UI hacker",
  public_repos: 18,
  public_gists: 99,
  followers: 22,
  following: 14,
};

export const repos = [
  {
    id: 63537249,
    node_id: "MDEwOlJlcG9zaXRvcnk2MzUzNzI0OQ==",
    name: "create-react-app",
    full_name: "facebook/create-react-app",
    private: false,
    owner: {},
    html_url: "https://github.com/facebook/create-react-app",
    description: "Set up a modern web app by running one command.",
    fork: false,
    created_at: "2016-07-17T14:55:11Z",
    updated_at: "2020-05-28T11:14:55Z",
    pushed_at: "2020-05-28T08:58:20Z",
    git_url: "git://github.com/facebook/create-react-app.git",
    ssh_url: "git@github.com:facebook/create-react-app.git",
    clone_url: "https://github.com/facebook/create-react-app.git",
    svn_url: "https://github.com/facebook/create-react-app",
    homepage: "https://create-react-app.dev",
    size: 14063,
    stargazers_count: 79027,
    watchers_count: 79027,
    language: "JavaScript",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: true,
    forks_count: 19075,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 622,
    forks: 19075,
    open_issues: 622,
    watchers: 79027,
    default_branch: "master",
  },
  {
    id: 86859683,
    node_id: "MDEwOlJlcG9zaXRvcnk4Njg1OTY4Mw==",
    name: "DelegatedRecoveryReferenceImplementation",
    full_name: "facebook/DelegatedRecoveryReferenceImplementation",
    private: false,
    owner: {
      login: "facebook",
      id: 69631,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
      avatar_url: "https://avatars3.githubusercontent.com/u/69631?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/facebook",
      html_url: "https://github.com/facebook",
      followers_url: "https://api.github.com/users/facebook/followers",
      following_url:
        "https://api.github.com/users/facebook/following{/other_user}",
      gists_url: "https://api.github.com/users/facebook/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/facebook/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/facebook/subscriptions",
      organizations_url: "https://api.github.com/users/facebook/orgs",
      repos_url: "https://api.github.com/users/facebook/repos",
      events_url: "https://api.github.com/users/facebook/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/facebook/received_events",
      type: "Organization",
      site_admin: false,
    },
    html_url:
      "https://github.com/facebook/DelegatedRecoveryReferenceImplementation",
    description:
      "The reference implementation of the Delegated Recovery specification found at https://github.com/facebook/DelegatedRecoverySpecification",
    fork: false,
    url:
      "https://api.github.com/repos/facebook/DelegatedRecoveryReferenceImplementation",
    created_at: "2017-03-31T20:54:56Z",
    updated_at: "2020-04-13T19:08:36Z",
    pushed_at: "2019-01-15T22:50:08Z",
    git_url:
      "git://github.com/facebook/DelegatedRecoveryReferenceImplementation.git",
    homepage: "",
    size: 81,
    stargazers_count: 22,
    watchers_count: 22,
    language: "Java",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    forks_count: 39,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    forks: 39,
    open_issues: 0,
    watchers: 22,
    default_branch: "master",
  },
];
